### ISSUE TITLE
豆瓣翻页抓取，代码里貌似没看到怎么实现的

### ISSUE THREAD

**Issue by ynztyl10** [fanpei91/doubanspiders#2]
“加载更多”，没看到如何实现

**Comment by Fuck-You-GFW** [comment]
貌似没翻页的, 只要看到是个"感兴趣"的链接, 就爬了, 不要翻页也能做到大范围爬取.

**Comment by ynztyl10** [comment]
为何不直接解析json？
https://movie.douban.com/j/search_subjects，接口中直接返回了subject的主页url，效率更高

**Comment by Fuck-You-GFW** [comment]
这项目烂尾啦. 你要想改进, 欢迎PR.

**Comment by xoyabc** [comment]
PR是啥意思？
