### ISSUE TITLE
演示站挂了？

### ISSUE THREAD

**Issue by dranshion** [fanpei91/doubanspiders#3]
还有其他的吗？

**Comment by fanpei91** [comment]
什么演示站？

**Comment by dranshion** [comment]
豆瓣采集的演示站啊



来自 魅族 PRO 6s



-------- 原始邮件 --------
发件人：fanpei91 <notifications@github.com>
时间：周二 12月26日 17:31
收件人：fanpei91/doubanspiders <doubanspiders@noreply.github.com>
抄送：dranshion <ccier@live.com>,Author <author@noreply.github.com>
主题：Re: [fanpei91/doubanspiders] 演示站挂了？ (#3)


什么演示站？

**Comment by fanpei91** [comment]
早关了
